# Generated by Django 3.2.7 on 2022-04-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='authors-profile-images/default.jpg', upload_to='authors-profile-images/')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('age', models.CharField(default=None, max_length=2)),
                ('occupation', models.CharField(default=None, max_length=50)),
                ('website', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150)),
                ('description', models.TextField(default=None)),
                ('mark', models.CharField(default=None, max_length=2)),
                ('cover', models.ImageField(default='books-cover-images/default.jpg', upload_to='books-cover-images/')),
                ('current_market_price', models.CharField(default=None, max_length=2)),
                ('pages', models.CharField(default=None, max_length=3)),
                ('owned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.nationalitie'),
        ),
    ]
