# Generated by Django 4.0.4 on 2022-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owned',
            new_name='physically_owned',
        ),
        migrations.AddField(
            model_name='book',
            name='virtually_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='current_market_price',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
