# Generated by Django 4.0.4 on 2022-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_rename_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='occupation',
            new_name='field',
        ),
    ]
