# Generated by Django 4.0.4 on 2022-05-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_field_rename_occupation_author_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='field',
        ),
    ]
