# Generated by Django 4.0.4 on 2022-05-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_author_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='author',
            name='field',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Books.field'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Books.nationalitie'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.ImageField(blank=True, default='authors-profile-images/default.jpg', upload_to='authors-profile-images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
